imports:
    - "without_repl_base.yaml"

output_dir: "output/output"

device:
  type: torch.device
  type_str: "cpu"
  index: 0

main:
  type: mlprogram.entrypoint.evaluate
  workspace_dir: "output/workspace"
  input_dir: "@/output_dir"
  output_dir: "@/output_dir"
  valid_dataset: "@/valid_dataset"
  model: "@/model"
  synthesizer: "@/synthesizer"
  metrics: {}
  top_n: []
  device: "@/device"
  n_process: 2